import { 
  Camera, 
  Utensils, 
  Brush, 
  Music, 
  Sparkles, 
  MapPin, 
  UsersRound, 
  PenLine, 
  Tent 
} from "lucide-react";

export type ServiceCategory = {
  id: number;
  name: string;
  icon: any;
  description: string;
  image: string;
};

export type ServiceProvider = {
  id: number;
  name: string;
  category: string;
  location: string;
  city: string;
  state: string;
  rating: number;
  reviewCount: number;
  image: string;
  featured: boolean;
  verified: boolean;
};

export const categories: ServiceCategory[] = [
  {
    id: 1,
    name: "Photographers",
    icon: Camera,
    description: "Capture your special moments with professional photographers",
    image: "https://images.unsplash.com/photo-1604017011826-d3b4c23f8914?ixlib=rb-4.0.3",
  },
  {
    id: 2,
    name: "Caterers",
    icon: Utensils,
    description: "Delicious food and beverage services for your events",
    image: "https://images.unsplash.com/photo-1555244162-803834f70033?ixlib=rb-4.0.3",
  },
  {
    id: 3,
    name: "Decorators",
    icon: Brush,
    description: "Transform your venue with beautiful decorations",
    image: "https://images.unsplash.com/photo-1519741347686-c1e331c5994e?ixlib=rb-4.0.3",
  },
  {
    id: 4,
    name: "Musicians",
    icon: Music,
    description: "Live music performers for a memorable experience",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6a3?ixlib=rb-4.0.3",
  },
  {
    id: 5,
    name: "Event Planners",
    icon: Sparkles,
    description: "Professional planners to organize your perfect event",
    image: "https://images.unsplash.com/photo-1505236858219-8359eb29e329?ixlib=rb-4.0.3",
  },
  {
    id: 6,
    name: "Venues",
    icon: MapPin,
    description: "Beautiful locations to host your special events",
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3",
  },
  {
    id: 7,
    name: "Wedding Planners",
    icon: UsersRound,
    description: "Specialists in planning your perfect wedding day",
    image: "https://images.unsplash.com/photo-1519741347686-c1e331c5994e?ixlib=rb-4.0.3",
  },
  {
    id: 8,
    name: "Invitation Designers",
    icon: PenLine,
    description: "Create beautiful custom invitations for your event",
    image: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?ixlib=rb-4.0.3",
  },
];

export const serviceProviders: ServiceProvider[] = [
  {
    id: 1,
    name: "Sharma Photography",
    category: "Photographers",
    location: "Connaught Place",
    city: "New Delhi",
    state: "Delhi",
    rating: 4.8,
    reviewCount: 127,
    image: "https://images.unsplash.com/photo-1604017011826-d3b4c23f8914?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 2,
    name: "Taste of India Caterers",
    category: "Caterers",
    location: "Juhu",
    city: "Mumbai",
    state: "Maharashtra",
    rating: 4.7,
    reviewCount: 89,
    image: "https://images.unsplash.com/photo-1555244162-803834f70033?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 3,
    name: "Royal Decorations",
    category: "Decorators",
    location: "Koramangala",
    city: "Bangalore",
    state: "Karnataka",
    rating: 4.5,
    reviewCount: 76,
    image: "https://images.unsplash.com/photo-1519741347686-c1e331c5994e?ixlib=rb-4.0.3",
    featured: true,
    verified: false
  },
  {
    id: 4,
    name: "Melody Makers",
    category: "Musicians",
    location: "Salt Lake City",
    city: "Kolkata",
    state: "West Bengal",
    rating: 4.9,
    reviewCount: 112,
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6a3?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 5,
    name: "Perfect Day Planners",
    category: "Event Planners",
    location: "Banjara Hills",
    city: "Hyderabad",
    state: "Telangana",
    rating: 4.6,
    reviewCount: 94,
    image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 6,
    name: "Grand Palace Venue",
    category: "Venues",
    location: "Alkapuri",
    city: "Vadodara",
    state: "Gujarat",
    rating: 4.7,
    reviewCount: 143,
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 7,
    name: "Wedding Bells",
    category: "Wedding Planners",
    location: "Aundh",
    city: "Pune",
    state: "Maharashtra",
    rating: 4.8,
    reviewCount: 87,
    image: "https://images.unsplash.com/photo-1519741347686-c1e331c5994e?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 8,
    name: "Creative Invites",
    category: "Invitation Designers",
    location: "Adyar",
    city: "Chennai",
    state: "Tamil Nadu",
    rating: 4.5,
    reviewCount: 65,
    image: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?ixlib=rb-4.0.3",
    featured: false,
    verified: false
  },
  {
    id: 9,
    name: "Pixel Perfect Studios",
    category: "Photographers",
    location: "Bandra",
    city: "Mumbai",
    state: "Maharashtra",
    rating: 4.9,
    reviewCount: 156,
    image: "https://images.unsplash.com/photo-1533747122396-48cc02fe7359?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 10,
    name: "Artistic Angles",
    category: "Photographers",
    location: "Gomti Nagar",
    city: "Lucknow",
    state: "Uttar Pradesh",
    rating: 4.6,
    reviewCount: 83,
    image: "https://images.unsplash.com/photo-1524142538600-8a934a8c965e?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 11,
    name: "Capture Chronicles",
    category: "Photographers",
    location: "MG Road",
    city: "Bangalore",
    state: "Karnataka",
    rating: 4.5,
    reviewCount: 91,
    image: "https://images.unsplash.com/photo-1476053055051-1062a3b8bbc5?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 12,
    name: "Moments in Frame",
    category: "Photographers",
    location: "Hauz Khas",
    city: "New Delhi",
    state: "Delhi",
    rating: 4.7,
    reviewCount: 114,
    image: "https://images.unsplash.com/photo-1553101862-09fe8f9a1457?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 13,
    name: "Lens Legacy",
    category: "Photographers",
    location: "Park Street",
    city: "Kolkata",
    state: "West Bengal",
    rating: 4.4,
    reviewCount: 78,
    image: "https://images.unsplash.com/photo-1508329988179-1df97f38478c?ixlib=rb-4.0.3",
    featured: false,
    verified: false
  },
  {
    id: 14,
    name: "Prime Photos",
    category: "Photographers",
    location: "Marine Drive",
    city: "Mumbai",
    state: "Maharashtra",
    rating: 4.9,
    reviewCount: 132,
    image: "https://images.unsplash.com/photo-1591280079250-979cfc588b6b?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 15,
    name: "Creative Captures",
    category: "Photographers",
    location: "Indiranagar",
    city: "Bangalore",
    state: "Karnataka",
    rating: 4.6,
    reviewCount: 95,
    image: "https://images.unsplash.com/photo-1554080353-a576cf803bda?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 16,
    name: "Memory Makers",
    category: "Photographers",
    location: "CP",
    city: "New Delhi",
    state: "Delhi",
    rating: 4.3,
    reviewCount: 72,
    image: "https://images.unsplash.com/photo-1534025484172-e03d4a7536b1?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 17,
    name: "Emotion Photographers",
    category: "Photographers",
    location: "Shivaji Nagar",
    city: "Pune",
    state: "Maharashtra",
    rating: 4.7,
    reviewCount: 108,
    image: "https://images.unsplash.com/photo-1604948501466-4e9c339b9c24?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 18,
    name: "Special Moments",
    category: "Photographers",
    location: "T Nagar",
    city: "Chennai",
    state: "Tamil Nadu",
    rating: 4.5,
    reviewCount: 86,
    image: "https://images.unsplash.com/photo-1560343787-b90cb337028e?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 19,
    name: "Royal Feast Caterers",
    category: "Caterers",
    location: "Andheri",
    city: "Mumbai",
    state: "Maharashtra",
    rating: 4.9,
    reviewCount: 143,
    image: "https://images.unsplash.com/photo-1555244162-803834f70033?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 20,
    name: "Delicious Delights",
    category: "Caterers",
    location: "Malad",
    city: "Mumbai",
    state: "Maharashtra",
    rating: 4.7,
    reviewCount: 98,
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 21,
    name: "Spice Route Catering",
    category: "Caterers",
    location: "Hauz Khas",
    city: "New Delhi",
    state: "Delhi",
    rating: 4.8,
    reviewCount: 127,
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 22,
    name: "Flavors of India",
    category: "Caterers",
    location: "Koramangala",
    city: "Bangalore",
    state: "Karnataka",
    rating: 4.6,
    reviewCount: 86,
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 23,
    name: "Gourmet Celebrations",
    category: "Caterers",
    location: "Egmore",
    city: "Chennai",
    state: "Tamil Nadu",
    rating: 4.5,
    reviewCount: 75,
    image: "https://images.unsplash.com/photo-1461009683693-342af2f2d6ce?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 24,
    name: "Perfect Platter",
    category: "Caterers",
    location: "Banjara Hills",
    city: "Hyderabad",
    state: "Telangana",
    rating: 4.7,
    reviewCount: 92,
    image: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 25,
    name: "Elite Eats",
    category: "Caterers",
    location: "Salt Lake",
    city: "Kolkata",
    state: "West Bengal",
    rating: 4.4,
    reviewCount: 81,
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?ixlib=rb-4.0.3",
    featured: true,
    verified: false
  },
  {
    id: 26,
    name: "Festive Foods",
    category: "Caterers",
    location: "Viman Nagar",
    city: "Pune",
    state: "Maharashtra",
    rating: 4.8,
    reviewCount: 105,
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 27,
    name: "Grand Cuisine",
    category: "Caterers",
    location: "Civil Lines",
    city: "Jaipur",
    state: "Rajasthan",
    rating: 4.6,
    reviewCount: 89,
    image: "https://images.unsplash.com/photo-1555244162-803834f70033?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 28,
    name: "Tasty Traditions",
    category: "Caterers",
    location: "Gomti Nagar",
    city: "Lucknow",
    state: "Uttar Pradesh",
    rating: 4.7,
    reviewCount: 94,
    image: "https://images.unsplash.com/photo-1675259113410-cd8b9a670708?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 29,
    name: "Dream Decor",
    category: "Decorators",
    location: "Worli",
    city: "Mumbai",
    state: "Maharashtra",
    rating: 4.9,
    reviewCount: 132,
    image: "https://images.unsplash.com/photo-1519741347686-c1e331c5994e?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 30,
    name: "Elegant Arrangements",
    category: "Decorators",
    location: "South Extension",
    city: "New Delhi",
    state: "Delhi",
    rating: 4.8,
    reviewCount: 116,
    image: "https://images.unsplash.com/photo-1603901623243-871b257f2816?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 31,
    name: "Creative Spaces",
    category: "Decorators",
    location: "Indiranagar",
    city: "Bangalore",
    state: "Karnataka",
    rating: 4.7,
    reviewCount: 103,
    image: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 32,
    name: "Floral Fantasy",
    category: "Decorators",
    location: "Anna Nagar",
    city: "Chennai",
    state: "Tamil Nadu",
    rating: 4.6,
    reviewCount: 89,
    image: "https://images.unsplash.com/photo-1519670734430-dc589b9c4e15?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 33,
    name: "Royal Themes",
    category: "Decorators",
    location: "Jubilee Hills",
    city: "Hyderabad",
    state: "Telangana",
    rating: 4.8,
    reviewCount: 127,
    image: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 34,
    name: "Perfect Setting",
    category: "Decorators",
    location: "Ballygunge",
    city: "Kolkata",
    state: "West Bengal",
    rating: 4.5,
    reviewCount: 91,
    image: "https://images.unsplash.com/photo-1519741347686-c1e331c5994e?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 35,
    name: "Vibrant Ventures",
    category: "Decorators",
    location: "Aundh",
    city: "Pune",
    state: "Maharashtra",
    rating: 4.7,
    reviewCount: 112,
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 36,
    name: "Artistic Arrangements",
    category: "Decorators",
    location: "Malviya Nagar",
    city: "Jaipur",
    state: "Rajasthan",
    rating: 4.6,
    reviewCount: 84,
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5793a?ixlib=rb-4.0.3",
    featured: false,
    verified: false
  },
  {
    id: 37,
    name: "Aesthetic Ambiance",
    category: "Decorators",
    location: "Vasant Vihar",
    city: "New Delhi",
    state: "Delhi",
    rating: 4.8,
    reviewCount: 97,
    image: "https://images.unsplash.com/photo-1532117892228-f25679962a16?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 38,
    name: "Grand Designs",
    category: "Decorators",
    location: "Alkapuri",
    city: "Vadodara",
    state: "Gujarat",
    rating: 4.5,
    reviewCount: 79,
    image: "https://images.unsplash.com/photo-1519741347686-c1e331c5994e?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 39,
    name: "Harmony Band",
    category: "Musicians",
    location: "Bandra",
    city: "Mumbai",
    state: "Maharashtra",
    rating: 4.9,
    reviewCount: 158,
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6a3?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 40,
    name: "Rhythm Ensemble",
    category: "Musicians",
    location: "Connaught Place",
    city: "New Delhi",
    state: "Delhi",
    rating: 4.8,
    reviewCount: 142,
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 41,
    name: "Sound Waves",
    category: "Musicians",
    location: "Koramangala",
    city: "Bangalore",
    state: "Karnataka",
    rating: 4.7,
    reviewCount: 124,
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 42,
    name: "Melodic Masters",
    category: "Musicians",
    location: "T Nagar",
    city: "Chennai",
    state: "Tamil Nadu",
    rating: 4.6,
    reviewCount: 118,
    image: "https://images.unsplash.com/photo-1501612780327-45045538702b?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 43,
    name: "Classical Crew",
    category: "Musicians",
    location: "Banjara Hills",
    city: "Hyderabad",
    state: "Telangana",
    rating: 4.8,
    reviewCount: 135,
    image: "https://images.unsplash.com/photo-1485561222158-e0271ee5793a?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 44,
    name: "Beat Blasters",
    category: "Musicians",
    location: "Park Street",
    city: "Kolkata",
    state: "West Bengal",
    rating: 4.7,
    reviewCount: 129,
    image: "https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 45,
    name: "Fusion Group",
    category: "Musicians",
    location: "Koregaon Park",
    city: "Pune",
    state: "Maharashtra",
    rating: 4.9,
    reviewCount: 152,
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 46,
    name: "Acoustic Artists",
    category: "Musicians",
    location: "C Scheme",
    city: "Jaipur",
    state: "Rajasthan",
    rating: 4.6,
    reviewCount: 107,
    image: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 47,
    name: "Soulful Strings",
    category: "Musicians",
    location: "Hiranandani",
    city: "Mumbai",
    state: "Maharashtra",
    rating: 4.8,
    reviewCount: 131,
    image: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 48,
    name: "Rhythm Masters",
    category: "Musicians",
    location: "MG Road",
    city: "Bangalore",
    state: "Karnataka",
    rating: 4.7,
    reviewCount: 126,
    image: "https://images.unsplash.com/photo-1501612780327-45045538702b?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 49,
    name: "Dream Events",
    category: "Event Planners",
    location: "Powai",
    city: "Mumbai",
    state: "Maharashtra",
    rating: 4.9,
    reviewCount: 148,
    image: "https://images.unsplash.com/photo-1505236858219-8359eb29e329?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 50,
    name: "Celebration Specialists",
    category: "Event Planners",
    location: "Pitampura",
    city: "New Delhi",
    state: "Delhi",
    rating: 4.8,
    reviewCount: 136,
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 51,
    name: "Perfect Day Events",
    category: "Event Planners",
    location: "Whitefield",
    city: "Bangalore",
    state: "Karnataka",
    rating: 4.7,
    reviewCount: 123,
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 52,
    name: "Royal Celebrations",
    category: "Event Planners",
    location: "Mylapore",
    city: "Chennai",
    state: "Tamil Nadu",
    rating: 4.6,
    reviewCount: 110,
    image: "https://images.unsplash.com/photo-1542931287-023b922fa89b?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 53,
    name: "Elite Occasions",
    category: "Event Planners",
    location: "Madhapur",
    city: "Hyderabad",
    state: "Telangana",
    rating: 4.8,
    reviewCount: 137,
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6a3?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 54,
    name: "Grand Celebrations",
    category: "Event Planners",
    location: "Alipore",
    city: "Kolkata",
    state: "West Bengal",
    rating: 4.7,
    reviewCount: 119,
    image: "https://images.unsplash.com/photo-1505236858219-8359eb29e329?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 55,
    name: "Signature Events",
    category: "Event Planners",
    location: "Deccan",
    city: "Pune",
    state: "Maharashtra",
    rating: 4.9,
    reviewCount: 154,
    image: "https://images.unsplash.com/photo-1519685358623-0523de8e8756?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 56,
    name: "Occasion Masters",
    category: "Event Planners",
    location: "Raja Park",
    city: "Jaipur",
    state: "Rajasthan",
    rating: 4.6,
    reviewCount: 105,
    image: "https://images.unsplash.com/photo-1513866942102-c3452613afde?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 57,
    name: "Memorable Moments",
    category: "Event Planners",
    location: "Defence Colony",
    city: "New Delhi",
    state: "Delhi",
    rating: 4.8,
    reviewCount: 140,
    image: "https://images.unsplash.com/photo-1505236858219-8359eb29e329?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 58,
    name: "Stellar Celebrations",
    category: "Event Planners",
    location: "Velachery",
    city: "Chennai",
    state: "Tamil Nadu",
    rating: 4.7,
    reviewCount: 121,
    image: "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 59,
    name: "Dream Weddings",
    category: "Wedding Planners",
    location: "Juhu",
    city: "Mumbai",
    state: "Maharashtra",
    rating: 4.9,
    reviewCount: 168,
    image: "https://images.unsplash.com/photo-1519741347686-c1e331c5994e?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 60,
    name: "Royal Matrimony",
    category: "Wedding Planners",
    location: "Vasant Kunj",
    city: "New Delhi",
    state: "Delhi",
    rating: 4.8,
    reviewCount: 155,
    image: "https://images.unsplash.com/photo-1507504031003-b417219a0fde?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 61,
    name: "Wedding Bells",
    category: "Wedding Planners",
    location: "HSR Layout",
    city: "Bangalore",
    state: "Karnataka",
    rating: 4.7,
    reviewCount: 143,
    image: "https://images.unsplash.com/photo-1519741347686-c1e331c5994e?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 62,
    name: "Perfect Unions",
    category: "Wedding Planners",
    location: "Nungambakkam",
    city: "Chennai",
    state: "Tamil Nadu",
    rating: 4.8,
    reviewCount: 149,
    image: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 63,
    name: "Wedding Wizards",
    category: "Wedding Planners",
    location: "Gachibowli",
    city: "Hyderabad",
    state: "Telangana",
    rating: 4.9,
    reviewCount: 152,
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 64,
    name: "Elegant Affairs",
    category: "Wedding Planners",
    location: "New Town",
    city: "Kolkata",
    state: "West Bengal",
    rating: 4.7,
    reviewCount: 138,
    image: "https://images.unsplash.com/photo-1519741347686-c1e331c5994e?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 65,
    name: "Matrimonial Magic",
    category: "Wedding Planners",
    location: "Kothrud",
    city: "Pune",
    state: "Maharashtra",
    rating: 4.8,
    reviewCount: 145,
    image: "https://images.unsplash.com/photo-1519741347686-c1e331c5994e?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 66,
    name: "Wedding Dreams",
    category: "Wedding Planners",
    location: "Model Town",
    city: "Jaipur",
    state: "Rajasthan",
    rating: 4.6,
    reviewCount: 127,
    image: "https://images.unsplash.com/photo-1519741347686-c1e331c5994e?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 67,
    name: "Forever Unions",
    category: "Wedding Planners",
    location: "Panchkula",
    city: "Chandigarh",
    state: "Punjab",
    rating: 4.7,
    reviewCount: 132,
    image: "https://images.unsplash.com/photo-1519741347686-c1e331c5994e?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 68,
    name: "Wedding Wonders",
    category: "Wedding Planners",
    location: "Saket",
    city: "New Delhi",
    state: "Delhi",
    rating: 4.8,
    reviewCount: 147,
    image: "https://images.unsplash.com/photo-1519741347686-c1e331c5994e?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 69,
    name: "Creative Cards",
    category: "Invitation Designers",
    location: "Andheri",
    city: "Mumbai",
    state: "Maharashtra",
    rating: 4.8,
    reviewCount: 122,
    image: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 70,
    name: "Elegant Invites",
    category: "Invitation Designers",
    location: "Greater Kailash",
    city: "New Delhi",
    state: "Delhi",
    rating: 4.7,
    reviewCount: 115,
    image: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 71,
    name: "Stylish Stationery",
    category: "Invitation Designers",
    location: "Jayanagar",
    city: "Bangalore",
    state: "Karnataka",
    rating: 4.6,
    reviewCount: 98,
    image: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 72,
    name: "Artistic Announcements",
    category: "Invitation Designers",
    location: "Adyar",
    city: "Chennai",
    state: "Tamil Nadu",
    rating: 4.7,
    reviewCount: 104,
    image: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 73,
    name: "Royal Cards",
    category: "Invitation Designers",
    location: "Jubilee Hills",
    city: "Hyderabad",
    state: "Telangana",
    rating: 4.8,
    reviewCount: 119,
    image: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 74,
    name: "Premium Prints",
    category: "Invitation Designers",
    location: "Bhowanipore",
    city: "Kolkata",
    state: "West Bengal",
    rating: 4.6,
    reviewCount: 95,
    image: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?ixlib=rb-4.0.3",
    featured: true,
    verified: false
  },
  {
    id: 75,
    name: "Designer Invites",
    category: "Invitation Designers",
    location: "Shivaji Nagar",
    city: "Pune",
    state: "Maharashtra",
    rating: 4.7,
    reviewCount: 109,
    image: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 76,
    name: "Artful Announcements",
    category: "Invitation Designers",
    location: "Vidhyadhar Nagar",
    city: "Jaipur",
    state: "Rajasthan",
    rating: 4.5,
    reviewCount: 87,
    image: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 77,
    name: "Invitation Innovation",
    category: "Invitation Designers",
    location: "Lokhandwala",
    city: "Mumbai",
    state: "Maharashtra",
    rating: 4.8,
    reviewCount: 124,
    image: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 78,
    name: "Perfect Prints",
    category: "Invitation Designers",
    location: "Malleswaram",
    city: "Bangalore",
    state: "Karnataka",
    rating: 4.6,
    reviewCount: 101,
    image: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 79,
    name: "Grand Palms Resort",
    category: "Venues",
    location: "Goregaon",
    city: "Mumbai",
    state: "Maharashtra",
    rating: 4.9,
    reviewCount: 175,
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 80,
    name: "Royal Gardens",
    category: "Venues",
    location: "Chattarpur",
    city: "New Delhi",
    state: "Delhi",
    rating: 4.8,
    reviewCount: 167,
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6a3?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 81,
    name: "Lotus Banquets",
    category: "Venues",
    location: "Electronic City",
    city: "Bangalore",
    state: "Karnataka",
    rating: 4.7,
    reviewCount: 154,
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6a3?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 82,
    name: "Seaside Celebrations",
    category: "Venues",
    location: "ECR",
    city: "Chennai",
    state: "Tamil Nadu",
    rating: 4.8,
    reviewCount: 163,
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 83,
    name: "Imperial Heights",
    category: "Venues",
    location: "Hitech City",
    city: "Hyderabad",
    state: "Telangana",
    rating: 4.9,
    reviewCount: 171,
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 84,
    name: "Riverside Retreat",
    category: "Venues",
    location: "Howrah",
    city: "Kolkata",
    state: "West Bengal",
    rating: 4.7,
    reviewCount: 152,
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 85,
    name: "Heritage Hall",
    category: "Venues",
    location: "Baner",
    city: "Pune",
    state: "Maharashtra",
    rating: 4.8,
    reviewCount: 158,
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 86,
    name: "Rajputana Palace",
    category: "Venues",
    location: "Amer Road",
    city: "Jaipur",
    state: "Rajasthan",
    rating: 4.9,
    reviewCount: 169,
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  },
  {
    id: 87,
    name: "Emerald Gardens",
    category: "Venues",
    location: "Sector 17",
    city: "Chandigarh",
    state: "Punjab",
    rating: 4.7,
    reviewCount: 156,
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3",
    featured: false,
    verified: true
  },
  {
    id: 88,
    name: "Crystal Ballroom",
    category: "Venues",
    location: "Aerocity",
    city: "New Delhi",
    state: "Delhi",
    rating: 4.8,
    reviewCount: 164,
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?ixlib=rb-4.0.3",
    featured: true,
    verified: true
  }
];

export const cities = [
  "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", 
  "Kolkata", "Ahmedabad", "Pune", "Jaipur", "Lucknow",
  "Kanpur", "Nagpur", "Indore", "Thane", "Bhopal",
  "Visakhapatnam", "Vadodara", "Ghaziabad", "Ludhiana", "Agra"
];

export const states = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
  "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand",
  "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur",
  "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab",
  "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura",
  "Uttar Pradesh", "Uttarakhand", "West Bengal", "Delhi", "Jammu and Kashmir"
];
